datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/work?useUnicode=true&characterEncoding=utf8
  name: root
  password: 123456
mybatis:
  mapper-locations: com/test/app/service/*/*/repository/mapper/**.xml
  type-aliases-package: com.test.app.api.app.area.model
  configuration:
    use-generated-keys: true #使用jdbc的getGeneratedKeys获取数据库自增主键值
    use-column-label: true  #使用列表标签替换列别名
    map-underscore-to-camel-case: true #开启驼峰命名转换
spring:
  application:
    name: app-service
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/work?useUnicode=true&characterEncoding=utf8
#    name: root
#    password: 123456
#    type: com.mchange.v2.c3p0.ComboPooledDataSource
#logging:
#  level:
#    root: debug
